apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
      - name: expiration
        image: thongkhoav/ticketing-expiration
        env:
          - name: KAFKA_URL
            value: "my-cluster-kafka-brokers.kafka.svc.cluster.local:9092"
          - name: KAFKA_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name #pod name
            value: ticketing
          - name: REDIS_URI
            value: "expiration-redis-srv"
          - name: REDIS_PORT
            value: "6379"


