apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: thongkhoav/ticketing-payments
        env:
          - name: KAFKA_URL
            value: "my-cluster-kafka-brokers.kafka.svc.cluster.local:9092"
          - name: KAFKA_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name #pod name
          - name: MONGO_URI
            value: "mongodb://payments-mongo-srv:27017/payments"
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000

